#pragma config(Motor,  port2,           turret,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           shoulder,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           extend,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           wrist,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           lmag,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           rmag,          tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int rightX;

int leftX;
int leftY;
bool on = true;


task armMovement() {
	while(on) {

		// Turret Movement

		if(vexRT[Btn6D]) {
			motor[turret] = -rightX;
			} else {
			motor[turret] = 0;

		}

	}
	// Arm Movement

	if(vexRT[Btn6U]) {
		motor[shoulder] = leftY;
		} else {
		motor[shoulder] = 0;
	}

	// Telescope Movement
	if(vexRT[Btn5D]) {
		motor[extend] = 90;
		} else if(vexRT[Btn5U]) {
		motor[extend] = -64;
	}
}

// Claw Movement
task claw() {
	while(on)   {
		// Claw Movement
		//Left Claw
		if(vexRT[Btn7R]) { //Close
			if(motor[lmag] <127) {
				motor[lmag] = motor[lmag] + 1;
				wait1Msec(5);
			}
		}

		else if (vexRT[Btn7L]) { //Open
			if(motor[rmag]> -127) {
				motor[rmag] = motor[rmag] - 1;
				wait1Msec(5);
			}
		}
	}

}

task main()
{StartTask(shoulder); // Starts "arm" Task
	// Turret
	// Extend Arm
	// Wrist
	// Shoulder
	// Claw



}
StartTask(claw);{ ; // Starts "Claw" Task"
	StartTask(armMovement);
	while(on) { // Keep Me Alive!!!!!!!!!!
		rightX = vexRT[Ch1]; // Refresh rightX variable with JoyStick input
		leftX = vexRT[Ch4]; // Refresh LeftX variable with Joy Stick's input
		leftY = vexRT[Ch3]; // Refresh leftY variable with JoyStick input
}
}
}
