#pragma config(Sensor, in1,    ptest,          sensorPotentiometer)
#pragma config(Motor,  port2,           motor1,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           smotor1,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           servo1,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           servo2,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           servo3,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port7,           servo4,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           smotor2,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           motor2,        tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int clawPos;
int clawPos2;
int potent;

task manipulation() {
	motor[motor2] = 0;
	while(true) {
		motor[motor1] = 100;

		if(vexRT[Btn7U]) {
			motor[motor2] = -100;
			} else if(in1 >= 9) {
			motor[motor1] = 0;
		}
		else {
			motor[motor2] = 0;
		}
		if(vexRT[Btn8L]) {
			clawPos++;
			wait1Msec(2);
			} else if(vexRT[Btn8U]) {
			clawPos--;
		}
	}
	if(vexRT[Btn8D]) {
		clawPos2++;
		wait1Msec(2);
		} else if(vexRT[Btn8R]) {
		clawPos2--;

	}
	if(vexRT[Btn5D]) {
		motor[smotor1] = 10;
	}
	if(vexRT[Btn6U]) {
		motor[smotor2] = -10;
	}
	motor[servo1] = clawPos;
	motor[servo2] = -clawPos;
	motor[servo3] = clawPos2;
	motor[servo4] = -clawPos2;
}

//Comment //Comment-ception!!!
task main(){
	StartTask(manipulation);
}
//StartTask(misbehave);
