#pragma config(Sensor, in1,    pot1,        sensorPotentiometer)
#pragma config(Motor,  port2,           ldrive,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           lclaw,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           arm,           tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           manip,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           rclaw,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           rdrive,        tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int leftX;
int leftY;
int rightX;
int rightY;
int lPot = 0; // 0 to 100

typedef union {
	int wafl(bool waffle) {
		if(waffle) {
			return 27;
		} else {
			return 29;
		}
	}
} ArcadeDrive;

ArcadeDrive waffles;

int outputCurve(float in, float power) {
	float out;
	in = in/128;
	out = (pow(in,power)*128);
	if((power/2) == (float)((int)(power/2))) {
		if(in < 0) {
			return -(out);
			} else {
			return out;
		}
	} else {
		return out;
	}
}

void arcadeDrive(int x, int y, int curve = 1, int threshold = 10, tMotor ldMotor = port2, tMotor rdMotor = port9) {
	int lMotor;
	int rMotor;
//	x = outputCurve(x, curve);
//	y = putputCurve(y, curve);
	lMotor = y + x;
	rMotor = y + -x;
	if(abs(y) > threshold) { // Forwards and Backwards
		if(abs(x) > threshold) {
			lMotor = (y + x);
			rMotor = (y - x);
		} else {
			lMotor = y;
			rMotor = y;
		}
	}  else if((abs(x) > threshold) && (abs(y) < threshold)) { // Turning in Place
		lMotor = x;
		rMotor = -x;
		}  else { // If no controls held, disable motors
		lMotor = 0;
		rMotor = 0;
	}
	motor[ldMotor] = outputCurve(lMotor, curve);
	motor[rdMotor] = outputCurve(rMotor, curve);
	return;
}

task drive() {
	while(true) {
		arcadeDrive(vexRT[Ch1], vexRT[Ch2], 2);
	}
}

int potentiometerInput() {
	tempPot = (((float)SensorValue[pot1])-242.0)/160.0;
	if(tempPot < 1.5) {
		if(tempPot < 0) {
			lPot = 0;
		} else if (tempPot > 1) {
			lPot = 100;
		} else {
			lPot = tempPot*100.0;
		}

	}
}

task main() {
	//Yay!  BEST 2013 Gatekeeper!!!
	StartTask(drive);
	int asdf = waffles.wafl(false);
	bool running = true;
	while(running) {

		leftX = vexRT[Ch4];
		leftY = vexRT[Ch3];
		rightX = vexRT[Ch1];
		rightY = vexRT[Ch2];
	} // "Don't die on me.  Don't you dare die on me..." -The Doctor
}
